
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 08 18:40:30 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 15;
  public static final int READ = 26;
  public static final int IDENT = 2;
  public static final int PLUS = 11;
  public static final int RPAREN = 18;
  public static final int RBRACE = 8;
  public static final int NOTZERO = 16;
  public static final int EQUAL = 10;
  public static final int CHAR = 5;
  public static final int SEMI = 9;
  public static final int RETURN = 28;
  public static final int MINUSMINUS = 22;
  public static final int RANGLE = 20;
  public static final int LPAREN = 17;
  public static final int LBRACE = 7;
  public static final int COMMA = 23;
  public static final int LANGLE = 19;
  public static final int EOF = 0;
  public static final int NUMBER = 3;
  public static final int DIV = 14;
  public static final int PROG = 6;
  public static final int PLUSPLUS = 21;
  public static final int MINUS = 12;
  public static final int PRINT = 25;
  public static final int CONST = 24;
  public static final int error = 1;
  public static final int NEW = 29;
  public static final int BOOL = 4;
  public static final int VOID = 27;
  public static final int MUL = 13;
}

